// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQUl9PwsXhtn0EK46AhjayS3iY-6zY5RU',
    appId: '1:473289865369:web:9a703532d7e37df8f32008',
    messagingSenderId: '473289865369',
    projectId: 'sem2-cee58',
    authDomain: 'sem2-cee58.firebaseapp.com',
    storageBucket: 'sem2-cee58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOEchr0-AJbLr1GrZbGtWGHYUrbfPRiso',
    appId: '1:473289865369:android:b912fc6587b833aaf32008',
    messagingSenderId: '473289865369',
    projectId: 'sem2-cee58',
    storageBucket: 'sem2-cee58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW85nz05TjdmfrZZQ2g6767kz8OHYmTNM',
    appId: '1:473289865369:ios:f550cfd977a36756f32008',
    messagingSenderId: '473289865369',
    projectId: 'sem2-cee58',
    storageBucket: 'sem2-cee58.appspot.com',
    iosBundleId: 'com.example.flutterWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW85nz05TjdmfrZZQ2g6767kz8OHYmTNM',
    appId: '1:473289865369:ios:f550cfd977a36756f32008',
    messagingSenderId: '473289865369',
    projectId: 'sem2-cee58',
    storageBucket: 'sem2-cee58.appspot.com',
    iosBundleId: 'com.example.flutterWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQUl9PwsXhtn0EK46AhjayS3iY-6zY5RU',
    appId: '1:473289865369:web:e24dedeb16a3a59af32008',
    messagingSenderId: '473289865369',
    projectId: 'sem2-cee58',
    authDomain: 'sem2-cee58.firebaseapp.com',
    storageBucket: 'sem2-cee58.appspot.com',
  );
}
